server:
  port: 8000
  

hello:
  greeting: 'Bonjour '
  position: 1
  case-type: camel
  style: Uppercase
  
app:
  random: ${random.uuid}
  
logging:
  file:
    path: .
    name:  server.log
    
  level:
    root: WARN
    org: 
      springframework.boot: DEBUG
      formation : debug
---
spring:
  config:
    activate:
      on-profile: prod
      
server:
  port: 7878